# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b7ff37efc2e47c6ce3438e50ae880bc5c7670d323d6f005434a0c397ba5948aabfcd1dbc3f2dd8e9ddf3b07b47d6bbb93671d918f58dda5c3a0baf929e8b5d5

test:
  secret_key_base: c29d952d6e0d5ea97d649bcd0c59f93d81247375d132577018357a2b86e0ff7653ee6b5e103ff0e55729cee193671a3108a4d510578b0a1a6166fd1f2bcc3d3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
